# version: "3.7"

services:
  gateway:
    build:
      context: ./gateway

  frontend:
    build:
      context: ./frontend
      args:
        CACHE_BUST: ${CACHE_BUST:-}

  backend:
    build:
      context: .
      args:
        CACHE_BUST: ${CACHE_BUST:-}
      secrets:
        - m2settings

secrets:
  m2settings:
    file: ~/.m2/settings.xml
