# version: "3.7"

services:
  gateway:
    build:
      context: ./gateway

  frontend:
    build:
      context: ./frontend

  backend:
    build:
      context: .
      secrets:
        - github_token

secrets:
  github_token:
    environment: GITHUB_TOKEN
